### ISSUE TITLE
ParseException: Unparseable date

### ISSUE THREAD

**Issue by throwrocks** [throwrocks/android-stock-rotation#4]
W/System.err: java.text.ParseException: Unparseable date: "1/15/2017 8:47 PM" (at offset 14)
W/System.err:     at java.text.DateFormat.parse(DateFormat.java:571)
W/System.err:     at rocks.athrow.android_stock_rotation.util.Utilities.getStringAsDate(Utilities.java:68)
W/System.err:     at rocks.athrow.android_stock_rotation.service.UpdateDBService.onHandleIntent(UpdateDBService.java:120)
W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:145)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by throwrocks** [comment]
This is fixed now using DATE_TIME_DISPLAY = "MM/dd/yy hh:mm:ss"
